### ISSUE TITLE
`lein watch` crashes on new project if `yarn` is used

### ISSUE THREAD

**Issue by Invertisment** [day8/re-frame-template#154]
If I run `yarn` after creating a project it crashes on `lein watch`.

I found a section about "use deps.cljs for JS dependencies". Is there a way to not edit that file by hand? 
Regular JS tooling allows to do this: `yarn add my-package` and move on to development. 
Editing the files by hand also complicates version upgrades if package version gets outdated.

Reproduction:

```
lein new re-frame re-frame-test
cd re-frame-test
yarn # install what's needed from package.json
lein watch
```

Output of `lein watch`:

```
OpenJDK 64-Bit Server VM warning: Options -Xverify:none and -noverify were deprecated in JDK 13 and will likely be removed in a future release.
lein-shadow - running: yarn --version
lein-shadow - 'yarn' version 1.22.4

lein-shadow - found existing package.json file at /home/_/clojure/re-frame-test/package.json
lein-shadow - reading node dependencies from /home/_/clojure/re-frame-test/src/cljs/deps.cljs
lein-shadow -  node package shadow-cljs@2.11.24 does not exist in package.json. Adding.
Error encountered performing task 'do' with profile(s): 'dev'
java.lang.IllegalArgumentException: Key must be integer
	at clojure.lang.APersistentVector.invoke(APersistentVector.java:294)
	at clojure.core$transduce.invokeStatic(core.clj:6881)
	at clojure.core$into.invokeStatic(core.clj:6899)
	at clojure.core$into.invoke(core.clj:6887)
	at leiningen.shadow$node_package_manager_install_missing_BANG_.invokeStatic(shadow.clj:255)
	at leiningen.shadow$node_package_manager_install_missing_BANG_.invoke(shadow.clj:242)
	at leiningen.shadow$node_deps_BANG_.invokeStatic(shadow.clj:273)
	at leiningen.shadow$node_deps_BANG_.invoke(shadow.clj:258)
	at leiningen.shadow$shadow.invokeStatic(shadow.clj:324)
	at leiningen.shadow$shadow.doInvoke(shadow.clj:301)
	at clojure.lang.RestFn.applyTo(RestFn.java:139)
	at clojure.lang.Var.applyTo(Var.java:705)
	at clojure.core$apply.invokeStatic(core.clj:667)
	at clojure.core$apply.invoke(core.clj:660)
	at leiningen.core.main$partial_task$fn__7330.doInvoke(main.clj:284)
	at clojure.lang.RestFn.applyTo(RestFn.java:139)
	at clojure.lang.AFunction$1.doInvoke(AFunction.java:31)
	at clojure.lang.RestFn.applyTo(RestFn.java:137)
	at clojure.core$apply.invokeStatic(core.clj:667)
	at clojure.core$apply.invoke(core.clj:660)
	at leiningen.core.main$apply_task.invokeStatic(main.clj:334)
	at leiningen.core.main$apply_task.invoke(main.clj:320)
	at leiningen.core.main$resolve_and_apply.invokeStatic(main.clj:343)
	at leiningen.core.main$resolve_and_apply.invoke(main.clj:336)
	at leiningen.do$do.invokeStatic(do.clj:40)
	at leiningen.do$do.doInvoke(do.clj:32)
	at clojure.lang.RestFn.applyTo(RestFn.java:139)
	at clojure.lang.Var.applyTo(Var.java:705)
	at clojure.core$apply.invokeStatic(core.clj:667)
	at clojure.core$apply.invoke(core.clj:660)
	at leiningen.core.main$partial_task$fn__7330.doInvoke(main.clj:284)
	at clojure.lang.RestFn.applyTo(RestFn.java:139)
	at clojure.lang.AFunction$1.doInvoke(AFunction.java:31)
	at clojure.lang.RestFn.applyTo(RestFn.java:137)
	at clojure.core$apply.invokeStatic(core.clj:667)
	at clojure.core$apply.invoke(core.clj:660)
	at leiningen.core.main$apply_task.invokeStatic(main.clj:334)
	at leiningen.core.main$apply_task.invoke(main.clj:320)
	at leiningen.with_profile$with_profiles_STAR_.invokeStatic(with_profile.clj:14)
	at leiningen.with_profile$with_profiles_STAR_.invoke(with_profile.clj:8)
	at leiningen.with_profile$apply_task_with_profiles.invokeStatic(with_profile.clj:53)
	at leiningen.with_profile$apply_task_with_profiles.invoke(with_profile.clj:45)
	at leiningen.with_profile$with_profile$fn__11310.invoke(with_profile.clj:85)
	at clojure.core$mapv$fn__8445.invoke(core.clj:6912)
	at clojure.core.protocols$fn__8159.invokeStatic(protocols.clj:168)
	at clojure.core.protocols$fn__8159.invoke(protocols.clj:124)
	at clojure.core.protocols$fn__8114$G__8109__8123.invoke(protocols.clj:19)
	at clojure.core.protocols$seq_reduce.invokeStatic(protocols.clj:31)
	at clojure.core.protocols$fn__8146.invokeStatic(protocols.clj:75)
	at clojure.core.protocols$fn__8146.invoke(protocols.clj:75)
	at clojure.core.protocols$fn__8088$G__8083__8101.invoke(protocols.clj:13)
	at clojure.core$reduce.invokeStatic(core.clj:6828)
	at clojure.core$mapv.invokeStatic(core.clj:6903)
	at clojure.core$mapv.invoke(core.clj:6903)
	at leiningen.with_profile$with_profile.invokeStatic(with_profile.clj:85)
	at leiningen.with_profile$with_profile.doInvoke(with_profile.clj:63)
	at clojure.lang.RestFn.applyTo(RestFn.java:146)
	at clojure.lang.Var.applyTo(Var.java:705)
	at clojure.core$apply.invokeStatic(core.clj:667)
	at clojure.core$apply.invoke(core.clj:660)
	at leiningen.core.main$partial_task$fn__7330.doInvoke(main.clj:284)
	at clojure.lang.RestFn.invoke(RestFn.java:410)
	at clojure.lang.AFn.applyToHelper(AFn.java:154)
	at clojure.lang.RestFn.applyTo(RestFn.java:132)
	at clojure.lang.AFunction$1.doInvoke(AFunction.java:31)
	at clojure.lang.RestFn.applyTo(RestFn.java:137)
	at clojure.core$apply.invokeStatic(core.clj:667)
	at clojure.core$apply.invoke(core.clj:660)
	at leiningen.core.main$apply_task.invokeStatic(main.clj:334)
	at leiningen.core.main$apply_task.invoke(main.clj:320)
	at leiningen.core.main$resolve_and_apply.invokeStatic(main.clj:343)
	at leiningen.core.main$resolve_and_apply.invoke(main.clj:336)
	at leiningen.core.main$_main$fn__7419.invoke(main.clj:453)
	at leiningen.core.main$_main.invokeStatic(main.clj:442)
	at leiningen.core.main$_main.doInvoke(main.clj:439)
	at clojure.lang.RestFn.applyTo(RestFn.java:137)
	at clojure.lang.Var.applyTo(Var.java:705)
	at clojure.core$apply.invokeStatic(core.clj:665)
	at clojure.main$main_opt.invokeStatic(main.clj:514)
	at clojure.main$main_opt.invoke(main.clj:510)
	at clojure.main$main.invokeStatic(main.clj:664)
	at clojure.main$main.doInvoke(main.clj:616)
	at clojure.lang.RestFn.applyTo(RestFn.java:137)
	at clojure.lang.Var.applyTo(Var.java:705)
	at clojure.main.main(main.java:40)
```

**Comment by superstructor** [comment]
Thanks for the feedback @Invertisment 

As of v2.0.0 released today we have entirely replaced Leiningen with a pure shadow-cljs build.

So now,
- lein-shadow no longer manages dependencies; so you have to use `npm` or `yarn` directly.
- `lein watch` becomes `npm run watch`
- `lein shadow --help` becomes `npx shadow-cljs --help`

Closing as this should resolve this and all related issues.

**Comment by ertugrulcetin** [comment]
@superstructor we can still use the old setup with leiningen, right?

**Comment by superstructor** [comment]
@ertugrulcetin Nope, leiningen is only used for generating the template (i.e. `lein new re-frame my-app ...`). Once generated, leiningen is not used to run the build anymore. 

In my opinion Leiningen is a great tool for some jobs that still has a strong place in back-end Clojure and front-end libraries (as can deploy jars etc).

But for front-end apps (not libs) built with shadow-cljs you get a better developer experience just using `npm` (or `yarn`) with `shadow-cljs`; e.g. auto-reloading of build configuration works.

Its a case of 'right tool for the job'.
