### ISSUE TITLE
lein uberjar fails on default project

### ISSUE THREAD

**Issue by aaelony** [Day8/re-frame-template#69]
I'm starting out with re-frame and discovered that `lein uberjar` fails from a fresh project via

```bash
lein new re-frame thetest +10x +cider +handler +garden +routes
cd thetest/
lein uberjar
```

```

Compiling ClojureScript...
Compiling "resources/public/js/compiled/app.js" from ["src/cljs"]...
Compiling "resources/public/js/compiled/app.js" failed.
clojure.lang.ExceptionInfo: failed compiling
...
...
Caused by: clojure.lang.ExceptionInfo: No such namespace: day8.re-frame.tracing, could not locate day8/re_frame/tracing.cljs, day8/re_frame/tracing.cljc, or JavaScript source providing "day8.re-frame.tracing"

... clj/thetest/src/cljs/thetest/events.cljs {:tag :cljs/analysis-error}
    at clojure.core$ex_info.invokeStatic(core.clj:4617)
    at clojure.core$ex_info.invoke(core.clj:4617)
    at cljs.analyzer$error.invokeStatic(analyzer.cljc:697)
    at cljs.analyzer$error.invoke(analyzer.cljc:693)
    at cljs.analyzer$error.invokeStatic(analyzer.cljc:695)
    at cljs.analyzer$error.invoke(analyzer.cljc:693)
    at cljs.analyzer$analyze_deps.invokeStatic(analyzer.cljc:2122)
    at cljs.analyzer$analyze_deps.invoke(analyzer.cljc:2096)
    at cljs.analyzer$ns_side_effects.invokeStatic(analyzer.cljc:3461)
    at cljs.analyzer$ns_side_effects.invoke(analyzer.cljc:3456)
    at cljs.analyzer$analyze_STAR_$fn__3036.invoke(analyzer.cljc:3580)
    at clojure.lang.PersistentVector.reduce(PersistentVector.java:341)
    at clojure.core$reduce.invokeStatic(core.clj:6544)
    at clojure.core$reduce.invoke(core.clj:6527)
    at cljs.analyzer$analyze_STAR_.invokeStatic(analyzer.cljc:3580)
    at cljs.analyzer$analyze_STAR_.invoke(analyzer.cljc:3570)
    at cljs.analyzer$analyze.invokeStatic(analyzer.cljc:3604)
    at cljs.analyzer$analyze.invoke(analyzer.cljc:3587)
    at cljs.compiler$emit_source.invokeStatic(compiler.cljc:1358)
    at cljs.compiler$emit_source.invoke(compiler.cljc:1337)
    at cljs.compiler$compile_file_STAR_$fn__4174.invoke(compiler.cljc:1437)
    at cljs.compiler$with_core_cljs.invokeStatic(compiler.cljc:1252)
    at cljs.compiler$with_core_cljs.invoke(compiler.cljc:1241)
    at cljs.compiler$compile_file_STAR_.invokeStatic(compiler.cljc:1422)
    at cljs.compiler$compile_file_STAR_.invoke(compiler.cljc:1415)
    at cljs.compiler$compile_file$fn__4205.invoke(compiler.cljc:1519)
    ... 58 more
Uberjar aborting because jar failed: Subprocess failed
```

 Any ideas on how to fix to get an uberjar?

Thank-you kindly

**Comment by aaelony** [comment]
@sveri in the re-frame channel points out that  adding `[day8.re-frame/tracing-stubs "0.5.1"]` to :dependencies in the project.clj will fix this issue.

Perhaps that can be added in the next or future version?

**Comment by gadfly361** [comment]
@aaelony Thanks for following up on this! I'll make sure it gets included with the next release.

**Comment by aaelony** [comment]
Sounds good, feel free to close this issue if it makes it to the next release.

**Comment by aaelony** [comment]
Just tried it and you are correct that `lein with-profile prod uberjar` works just fine, out of the box.
Perhaps I missed that in the docs or they can be added.

Many thanks, @gadfly361

**Comment by gadfly361** [comment]
@aaelony Thanks for confirming!  The docs are definitely incorrect, so I'll go ahead and update them.
