### ISSUE TITLE
run time error after create a project using the template

### ISSUE THREAD

**Issue by wqhhust** [Day8/re-frame-template#7]
I first run

lein new re-frame re-frame +re-com

then it has the following error:
oracle@SomeHost ~/clojure/lein/re-frame $ lein clean
oracle@SomeHost ~/clojure/lein/re-frame $ lein figwheel dev
Figwheel: Starting server at http://localhost:3449
Focusing on build ids: dev
Compiling "resources/public/js/compiled/app.js" from ["src/cljs"]...
Compiling "resources/public/js/compiled/app.js" failed.
clojure.lang.ExceptionInfo: failed compiling file:src/cljs/re_frame/views.cljs
 at clojure.core$ex_info.invoke (core.clj:4403)
Caused by: clojure.lang.ExceptionInfo: Assert failed: Circular dependency detected [re-frame.views re-frame.core]
(every? (fn* [p1__1802#] (not (contains? *cljs-dep-set* p1__1802#))) deps) at line 1 /home/oracle/clojure/lein/re-frame/src/cljs/re_frame/core.cljs
 at clojure.core$ex_info.invoke (core.clj:4403)
Caused by: java.lang.AssertionError: Assert failed: Circular dependency detected [re-frame.views re-frame.core]
(every? (fn* [p1__1802#] (not (contains? *cljs-dep-set* p1__1802#))) deps)
 at cljs.analyzer$analyze_deps.invoke (analyzer.clj:1255)

clojure.lang.ExceptionInfo: Assert failed: Circular dependency detected [re-frame.views re-frame.core]
(every? (fn* [p1__1802#] (not (contains? *cljs-dep-set* p1__1802#))) deps) at line 1 /home/oracle/clojure/lein/re-frame/src/cljs/re_frame/core.cljs {:tag :cljs/analysis-error, :file "/home/oracle/clojure/lein/re-frame/src/cljs/re_frame/core.cljs", :line 1, :column 1}
	at clojure.core$ex_info.invoke(core.clj:4403)
	at cljs.analyzer$error.invoke(analyzer.clj:380)
	at cljs.analyzer$analyze_seq.invoke(analyzer.clj:1859)
	at cljs.analyzer$analyze$fn__2170.invoke(analyzer.clj:1953)
	at cljs.analyzer$analyze.invoke(analyzer.clj:1946)
	at cljs.analyzer$analyze_file$fn__2221.invoke(analyzer.clj:2190)
	at cljs.analyzer$analyze_file.invoke(analyzer.clj:2185)
	at cljs.analyzer$analyze_deps.invoke(analyzer.clj:1262)
	at cljs.analyzer$eval1922$fn__1924.invoke(analyzer.clj:1516)
	at clojure.lang.MultiFn.invoke(MultiFn.java:249)
	at cljs.analyzer$analyze_seq.invoke(analyzer.clj:1861)
	at cljs.analyzer$analyze$fn__2170.invoke(analyzer.clj:1953)
	at cljs.analyzer$analyze.invoke(analyzer.clj:1946)
	at cljs.analyzer$analyze_file$fn__2221.invoke(analyzer.clj:2190)
	at cljs.analyzer$analyze_file.invoke(analyzer.clj:2185)
	at figwheel_sidecar.repl$analyze_build.invoke(repl.clj:252)
	at figwheel_sidecar.repl$analyze_builds.invoke(repl.clj:257)
	at figwheel_sidecar.repl$run_autobuilder_helper.invoke(repl.clj:305)
	at figwheel_sidecar.repl$start_autobuild.invoke(repl.clj:376)
	at figwheel_sidecar.repl$run_autobuilder.invoke(repl.clj:535)
	at user$eval17935.invoke(form-init8107703929753713336.clj:1)
	at clojure.lang.Compiler.eval(Compiler.java:6703)
	at clojure.lang.Compiler.eval(Compiler.java:6693)
	at clojure.lang.Compiler.load(Compiler.java:7130)
	at clojure.lang.Compiler.loadFile(Compiler.java:7086)
	at clojure.main$load_script.invoke(main.clj:274)
	at clojure.main$init_opt.invoke(main.clj:279)
	at clojure.main$initialize.invoke(main.clj:307)
	at clojure.main$null_opt.invoke(main.clj:342)
	at clojure.main$main.doInvoke(main.clj:420)
	at clojure.lang.RestFn.invoke(RestFn.java:421)
	at clojure.lang.Var.invoke(Var.java:383)
	at clojure.lang.AFn.applyToHelper(AFn.java:156)
	at clojure.lang.Var.applyTo(Var.java:700)
	at clojure.main.main(main.java:37)
Caused by: java.lang.AssertionError: Assert failed: Circular dependency detected [re-frame.views re-frame.core]
(every? (fn* [p1__1802#] (not (contains? *cljs-dep-set* p1__1802#))) deps)
	at cljs.analyzer$analyze_deps.invoke(analyzer.clj:1255)
	at cljs.analyzer$eval1922$fn__1924.invoke(analyzer.clj:1516)
	at clojure.lang.MultiFn.invoke(MultiFn.java:249)
	at cljs.analyzer$analyze_seq.invoke(analyzer.clj:1861)
	... 32 more
Subprocess failed

**Comment by wqhhust** [comment]
After I used a different project name as following, then it works.
lein new re-frame test_frame +re-com

it's strange why I can't name the project as re-frame.

**Comment by mike-thompson-day8** [comment]
> it's strange why I can't name the project as re-frame.

It results in a namespace clash.
