### ISSUE TITLE
Deploy to heroku doesn't work with +10x profile generated project.

### ISSUE THREAD

**Issue by rockBreaker** [Day8/re-frame-template#75]
I get this exception: 

```
remote:        Compiling ["resources/public/js/compiled/app.js"] failed.
remote:        clojure.lang.ExceptionInfo: failed compiling file:/tmp/build_deac098dd63d4bfb3506640e8f2dad2f/src/cljs/ccsoli2/events.cljs {:file #object[java.io.File 0x225fc6a2 "/tmp/build_deac098dd63d4bfb3506640e8f2dad2f/src/cljs/ccsoli2/events.cljs"]}
remote:        	at clojure.core$ex_info.invokeStatic(core.clj:4617)
remote:        	at clojure.core$ex_info.invoke(core.clj:4617)
remote:        	at cljs.compiler$compile_file$fn__3702.invoke(compiler.cljc:1562)
remote:        	at cljs.compiler$compile_file.invokeStatic(compiler.cljc:1522)
remote:        	at cljs.compiler$compile_file.invoke(compiler.cljc:1498)
remote:        	at cljs.closure$compile_file.invokeStatic(closure.clj:573)
remote:        	at cljs.closure$compile_file.invoke(closure.clj:564)
remote:        	at cljs.closure$fn__5124.invokeStatic(closure.clj:653)
remote:        	at cljs.closure$fn__5124.invoke(closure.clj:647)
remote:        	at cljs.closure$fn__5052$G__5045__5059.invoke(closure.clj:521)
remote:        	at cljs.closure$fn__5128.invokeStatic(closure.clj:662)
remote:        	at cljs.closure$fn__5128.invoke(closure.clj:647)
remote:        	at cljs.closure$fn__5052$G__5045__5059.invoke(closure.clj:521)
remote:        	at cljs.closure$compile_sources$iter__5250__5254$fn__5255.invoke(closure.clj:1011)
remote:        	at clojure.lang.LazySeq.sval(LazySeq.java:40)
remote:        	at clojure.lang.LazySeq.seq(LazySeq.java:49)
remote:        	at clojure.lang.Cons.next(Cons.java:39)
remote:        	at clojure.lang.RT.next(RT.java:688)
remote:        	at clojure.core$next__4341.invokeStatic(core.clj:64)
remote:        	at clojure.core$dorun.invokeStatic(core.clj:3033)
remote:        	at clojure.core$doall.invokeStatic(core.clj:3039)
remote:        	at clojure.core$doall.invoke(core.clj:3039)
remote:        	at cljs.closure$compile_sources.invokeStatic(closure.clj:1007)
remote:        	at cljs.closure$compile_sources.invoke(closure.clj:996)
remote:        	at cljs.closure$build.invokeStatic(closure.clj:2817)
remote:        	at cljs.closure$build.invoke(closure.clj:2718)
remote:        	at cljs.build.api$build.invokeStatic(api.clj:208)
remote:        	at cljs.build.api$build.invoke(api.clj:189)
remote:        	at cljs.build.api$build.invokeStatic(api.clj:195)
remote:        	at cljs.build.api$build.invoke(api.clj:189)
remote:        	at cljsbuild.compiler$compile_cljs$fn__550.invoke(compiler.clj:61)
remote:        	at cljsbuild.compiler$compile_cljs.invokeStatic(compiler.clj:60)
remote:        	at cljsbuild.compiler$compile_cljs.invoke(compiler.clj:48)
remote:        	at cljsbuild.compiler$run_compiler.invokeStatic(compiler.clj:168)
remote:        	at cljsbuild.compiler$run_compiler.invoke(compiler.clj:129)
remote:        	at user$eval665$iter__701__705$fn__706$fn__724.invoke(form-init641934052571790955.clj:1)
remote:        	at user$eval665$iter__701__705$fn__706.invoke(form-init641934052571790955.clj:1)
remote:        	at clojure.lang.LazySeq.sval(LazySeq.java:40)
remote:        	at clojure.lang.LazySeq.seq(LazySeq.java:49)
remote:        	at clojure.lang.RT.seq(RT.java:521)
remote:        	at clojure.core$seq__4357.invokeStatic(core.clj:137)
remote:        	at clojure.core$dorun.invokeStatic(core.clj:3024)
remote:        	at clojure.core$doall.invokeStatic(core.clj:3039)
remote:        	at clojure.core$doall.invoke(core.clj:3039)
remote:        	at user$eval665.invokeStatic(form-init641934052571790955.clj:1)
remote:        	at user$eval665.invoke(form-init641934052571790955.clj:1)
remote:        	at clojure.lang.Compiler.eval(Compiler.java:6927)
remote:        	at clojure.lang.Compiler.eval(Compiler.java:6917)
remote:        	at clojure.lang.Compiler.load(Compiler.java:7379)
remote:        	at clojure.lang.Compiler.loadFile(Compiler.java:7317)
remote:        	at clojure.main$load_script.invokeStatic(main.clj:275)
remote:        	at clojure.main$init_opt.invokeStatic(main.clj:277)
remote:        	at clojure.main$init_opt.invoke(main.clj:277)
remote:        	at clojure.main$initialize.invokeStatic(main.clj:308)
remote:        	at clojure.main$null_opt.invokeStatic(main.clj:342)
remote:        	at clojure.main$null_opt.invoke(main.clj:339)
remote:        	at clojure.main$main.invokeStatic(main.clj:421)
remote:        	at clojure.main$main.doInvoke(main.clj:384)
remote:        	at clojure.lang.RestFn.invoke(RestFn.java:421)
remote:        	at clojure.lang.Var.invoke(Var.java:383)
remote:        	at clojure.lang.AFn.applyToHelper(AFn.java:156)
remote:        	at clojure.lang.Var.applyTo(Var.java:700)
remote:        	at clojure.main.main(main.java:37)
remote:        Caused by: clojure.lang.ExceptionInfo: No such namespace: day8.re-frame.tracing, could not locate day8/re_frame/tracing.cljs, day8/re_frame/tracing.cljc, or JavaScript source providing "day8.re-frame.tracing" in file /tmp/build_deac098dd63d4bfb3506640e8f2dad2f/src/cljs/ccsoli2/events.cljs {:tag :cljs/analysis-error}
remote:        	at clojure.core$ex_info.invokeStatic(core.clj:4617)
remote:        	at clojure.core$ex_info.invoke(core.clj:4617)
remote:        	at cljs.analyzer$error.invokeStatic(analyzer.cljc:697)
remote:        	at cljs.analyzer$error.invoke(analyzer.cljc:693)
remote:        	at cljs.analyzer$error.invokeStatic(analyzer.cljc:695)
remote:        	at cljs.analyzer$error.invoke(analyzer.cljc:693)
remote:        	at cljs.analyzer$analyze_deps.invokeStatic(analyzer.cljc:2129)
remote:        	at cljs.analyzer$analyze_deps.invoke(analyzer.cljc:2103)
remote:        	at cljs.analyzer$ns_side_effects.invokeStatic(analyzer.cljc:3476)
remote:        	at cljs.analyzer$ns_side_effects.invoke(analyzer.cljc:3471)
remote:        	at cljs.analyzer$analyze_STAR_$fn__2510.invoke(analyzer.cljc:3596)
remote:        	at clojure.lang.PersistentVector.reduce(PersistentVector.java:341)
remote:        	at clojure.core$reduce.invokeStatic(core.clj:6544)
remote:        	at clojure.core$reduce.invoke(core.clj:6527)
remote:        	at cljs.analyzer$analyze_STAR_.invokeStatic(analyzer.cljc:3596)
remote:        	at cljs.analyzer$analyze_STAR_.invoke(analyzer.cljc:3586)
remote:        	at cljs.analyzer$analyze.invokeStatic(analyzer.cljc:3616)
remote:        	at cljs.analyzer$analyze.invoke(analyzer.cljc:3598)
remote:        	at cljs.compiler$emit_source.invokeStatic(compiler.cljc:1386)
remote:        	at cljs.compiler$emit_source.invoke(compiler.cljc:1365)
remote:        	at cljs.compiler$compile_file_STAR_$fn__3672.invoke(compiler.cljc:1467)
remote:        	at cljs.compiler$with_core_cljs.invokeStatic(compiler.cljc:1285)
remote:        	at cljs.compiler$with_core_cljs.invoke(compiler.cljc:1274)
remote:        	at cljs.compiler$compile_file_STAR_.invokeStatic(compiler.cljc:1451)
remote:        	at cljs.compiler$compile_file_STAR_.invoke(compiler.cljc:1444)
remote:        	at cljs.compiler$compile_file$fn__3702.invoke(compiler.cljc:1547)
remote:        	... 60 more
remote:        Uberjar aborting because jar failed: Subprocess failed
remote:  !     Failed to build.
remote:  !     Push rejected, failed to compile Clojure (Leiningen 2) app.
remote:
remote:  !     Push failed
```

When i create a fresh project using this:

```
lein new re-frame ccsoli2 +less +10x +test +aliases +handler +routes +re-pressed +re-com
```

However when i create a project without +10x:

```
lein new re-frame ccsoli3 +less +re-frisk +test +aliases +handler +routes +re-pressed +re-com
```

It works correctly.

My guess is 
```
Caused by: clojure.lang.ExceptionInfo: No such namespace: day8.re-frame.tracing, could not locate day8/re_frame/tracing.cljs, day8/re_frame/tracing.cljc, or JavaScript source providing "day8.re-frame.tracing" in file /tmp/build_deac098dd63d4bfb3506640e8f2dad2f/src/cljs/ccsoli2/events.cljs {:tag :cljs/analysis-error}
```

Is because of the `day8.re-frame/tracing-stubs` replacing the tracing.cljc in the 

```
:prod { :dependencies [[day8.re-frame/tracing-stubs "0.5.1"]]}
```

Part of the project.clj. 

Easy repro steps.
`lein new re-frame ccsoli3 +less +10x +test +aliases +handler +routes +re-pressed +re-com`
`heroku create`
`git push heroku master`

Then just remove the +10x for a new project and it works.

**Comment by rockBreaker** [comment]
Hi this might be a pebcak but to get i managed to get it working.

Essentially when heroku builds the app it uses
`lein uberjar`

The readme says to use
`lein with-profile prod uberjar`

I added the config vars via

https://devcenter.heroku.com/articles/clojure-support#customizing-the-build

```
LEIN_BUILD_TASK                 with-profile prod uberjar
LEIN_INCLUDE_IN_SLUG      yes

```

and it works with the following 

```
lein new re-frame ccsoli2 +less +10x +test +aliases +handler +routes +re-pressed +re-com
``` 

Fresh project.

**Comment by rockBreaker** [comment]
Ah i just saw this was a duplicate. Apologies for this.

**Comment by gadfly361** [comment]
@rockBreaker Glad you were able to get it working!

**Comment by rockBreaker** [comment]
Yeah me too haha :D. 
Sorry for not searching the closed issues. At least this way if it happens to anyone else for heroku at least, there are some steps for getting it working.
